/**
 * Static v3 contract shared by validation and protocol tests.
 *
 * Kiro CLI v3 is the runtime. This module is data-only and never edits Kiro
 * settings, sessions, or permission files.
 */
export const ITOPS_V3_SPECIALIST_AGENTS = [
  "itops-splunk",
  "itops-sql-server",
  "itops-mongodb-docdb",
  "itops-dynatrace",
  "itops-argocd",
  "itops-source-code",
] as const;

export const ITOPS_V3_MCP_TOOLS = [
  "itops-core/jira_search",
  "itops-core/jira_get_issue",
  "itops-core/confluence_search",
  "itops-core/confluence_get_page",
  "itops-core/report_write",
  "itops-core/artifact_write_splunk_dashboard",
  "itops-core/itops_core_health",
  "itops-splunk/splunk_search",
  "itops-splunk/splunk_list_indexes",
  "itops-splunk/splunk_generate_dashboard_xml",
  "itops-splunk/splunk_health",
  "itops-sql-server/sql_list_connections",
  "itops-sql-server/sql_query",
  "itops-sql-server/sql_list_schema",
  "itops-sql-server/sql_health",
  "itops-mongodb-docdb/mongodb_list_connections",
  "itops-mongodb-docdb/mongodb_list_databases",
  "itops-mongodb-docdb/mongodb_find",
  "itops-mongodb-docdb/mongodb_aggregate",
  "itops-mongodb-docdb/mongodb_list_collections",
  "itops-mongodb-docdb/mongodb_sample_schema",
  "itops-mongodb-docdb/mongodb_health",
  "itops-argocd/argocd_list_applications",
  "itops-argocd/argocd_get_application",
  "itops-argocd/argocd_resource_tree",
  "itops-argocd/argocd_managed_resources",
  "itops-argocd/argocd_application_events",
  "itops-argocd/argocd_health",
  "itops-source-code/bitbucket_tree",
  "itops-source-code/bitbucket_read_file",
  "itops-source-code/bitbucket_commits",
  "itops-source-code/bitbucket_commit_diff",
  "itops-source-code/bitbucket_pull_request",
  "itops-source-code/bitbucket_pipelines",
  "itops-source-code/gitlab_tree",
  "itops-source-code/gitlab_read_file",
  "itops-source-code/gitlab_code_search",
  "itops-source-code/gitlab_commits",
  "itops-source-code/gitlab_commit_diff",
  "itops-source-code/gitlab_merge_request",
  "itops-source-code/gitlab_pipelines",
  "itops-source-code/gitlab_job_trace",
  "itops-source-code/source_code_health",
  "dynatrace-platform/nl2dql",
  "dynatrace-platform/dql2nl",
  "dynatrace-platform/dynatrace-conversation",
  "dynatrace-platform/execute-dql",
] as const;
